### ISSUE TITLE
Ability to disable auto-change video clip.

### ISSUE THREAD

**Issue by chokosticks** [Azure/video-analyzer-widgets#139]
Hi,

it would be nice to be able to disable the widget to automatically jump to the next video sequence.
Specially useful when there are many small video-sequences during a day.

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.

**Comment by chokosticks** [comment]
Hi,

I'm just wondering what's the argument behind retiring Azure Video Analyzer?

**Comment by jasonxian-msft** [comment]
Hi @chokosticks, the AVA Edge modules will remain functional until December 01, 2022.

**Comment by naiteeks** [comment]
Closing issue.
