### ISSUE TITLE
Duplicate set of controls on the widget

### ISSUE THREAD

**Issue by duggaraju** [Azure/video-analyzer-widgets#17]
Try the examples/sample.html and click start playback twice. The widget will have two rows of duplicate controls
![image](https://user-images.githubusercontent.com/3238784/132074429-a2d35b87-792f-4244-8a88-93053600cd85.png)

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
