### ISSUE TITLE
[Low Latency Playback] Shaka RTSP plugin must handle MSE errors and stop the RTSP pipeline (restart source from widgets).

### ISSUE THREAD

**Issue by RaymondCheng** [Azure/video-analyzer-widgets#23]
Cross-reference: MSAzure # 10619548.

Reset source on 3016/PIPELINE_ERROR_DECODE.

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
